### model
model_name_or_path: llava-hf/llava-1.5-7b-hf
print_param_status: true

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: mllm_pt_demo
template: llava
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llava1_5-7b/full/pt
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 100.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
train_mm_proj_only: true

### eval
do_eval: false